### ISSUE TITLE
gh-demo.kubeflow.org is down

### ISSUE THREAD

**Issue by jlewi** [kubeflow/examples#118]
See kubeflow/kubeflow#871

It looks like
https://github.com/kubeflow/testing/blob/master/dev-kubeflow-org/ks-app/components/issue-summarization-ui.jsonnet

Is setting the ServiceType to ClusterIP and not NodePort which was causing the ingress not to be setup.

It also look like there is no ksonnet component for setting up the ingress to expose it via ingress

Was the issue to originally expose it
kubeflow/examples/issues/62

@ankushagarwal Do you recall how you originally setup the ingress? Did you not check it in?

/cc @ankushagarwal 
/assign @jlewi

**Comment by jlewi** [comment]
Looks like we also didn't reserve a static ip for it in dev.kubeflow.org.

**Comment by jlewi** [comment]
The ingress is now created; waiting for DNS to propogate.

issue-summarization-ui is crashing though 

```
Traceback (most recent call last):
  File "app.py", line 14, in <module>
    GITHUB_TOKEN = os.environ['GITHUB_TOKEN']
  File "/usr/local/lib/python3.6/os.py", line 669, in __getitem__
    raise KeyError(key) from None
KeyError: 'GITHUB_TOKEN'
```

This was the issue discussed on slack. The component is trying to get the GITHUB_TOKEN from a param and not a secret.
