### ISSUE TITLE
[object_detection] Error in create-pet-record-job: pet_label_map not found

### ISSUE THREAD

**Issue by Oblynx** [kubeflow/examples#272]
Following the instructions for the object recognition example, creating the TF pet records fails for me after applying the ks component `ks apply ${ENV} -c create-pet-record-job`.

Pod logs:
```
oblivion@ksamtsak-office:~/clusters/kosamara-kubeflow-cpu11/kubeflow/ks-object-recognition$ kubectl logs create-pet-record-job-mjj82 
Traceback (most recent call last):
  File "/models/research/object_detection/dataset_tools/create_pet_tf_record.py", line 318, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "/models/research/object_detection/dataset_tools/create_pet_tf_record.py", line 271, in main
    label_map_dict = label_map_util.get_label_map_dict(FLAGS.label_map_path)
  File "/models/research/object_detection/utils/label_map_util.py", line 163, in get_label_map_dict
    label_map = load_labelmap(label_map_path)
  File "/models/research/object_detection/utils/label_map_util.py", line 132, in load_labelmap
    label_map_string = fid.read()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/lib/io/file_io.py", line 125, in read
    self._preread_check()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/lib/io/file_io.py", line 85, in _preread_check
    compat.as_bytes(self.__name), 1024 * 512, status)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/errors_impl.py", line 519, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: models/research/object_detection/data/pet_label_map.pbtxt; No such file or directory
```

**Comment by Oblynx** [comment]
Fix is trivial; the file path misses a slash at the beginning. After fixing:

```
oblivion@ksamtsak-office:~/clusters/kosamara-kubeflow-cpu11/kubeflow/ks-object-recognition$ kubectl logs create-pet-record-job-7h6fq
/models/research/object_detection/utils/dataset_util.py:75: FutureWarning: The behavior of this method will change in future versions. Use specific 'len(elem)' or 'elem is not None' test instead.
  if not xml:
WARNING:root:Could not find /pets_data/annotations/xmls/Abyssinian_104.xml, ignoring example.
WARNING:root:Could not find /pets_data/annotations/xmls/Bengal_175.xml, ignoring example.
WARNING:root:Could not find /pets_data/annotations/xmls/Egyptian_Mau_14.xml, ignoring example.
WARNING:root:Could not find /pets_data/annotations/xmls/Ragdoll_199.xml, ignoring example.
WARNING:root:Could not find /pets_data/annotations/xmls/Egyptian_Mau_186.xml, ignoring example.
WARNING:root:Could not find /pets_data/annotations/xmls/saint_bernard_15.xml, ignoring example.
WARNING:root:Could not find /pets_data/annotations/xmls/Bengal_111.xml, ignoring example.
WARNING:root:Could not find /pets_data/annotations/xmls/samoyed_10.xml, ignoring example.
WARNING:root:Could not find /pets_data/annotations/xmls/Egyptian_Mau_156.xml, ignoring example.
```
