### ISSUE TITLE
[code_search] training on GPU fails with import error

### ISSUE THREAD

**Issue by jlewi** [kubeflow/examples#310]
I tried to run training on GPU and it failed with the following import error.

```
Traceback (most recent call last):
  File "/usr/local/bin/t2t-trainer", line 23, in <module>
    from tensor2tensor.bin import t2t_trainer
  File "/usr/local/lib/python2.7/dist-packages/tensor2tensor/bin/t2t_trainer.py", line 23, in <module>
    from tensor2tensor import models  # pylint: disable=unused-import
  File "/usr/local/lib/python2.7/dist-packages/tensor2tensor/models/__init__.py", line 21, in <module>
    from tensor2tensor.layers import modalities  # pylint: disable=g-import-not-at-top
  File "/usr/local/lib/python2.7/dist-packages/tensor2tensor/layers/modalities.py", line 21, in <module>
    from tensor2tensor.layers import common_layers
  File "/usr/local/lib/python2.7/dist-packages/tensor2tensor/layers/common_layers.py", line 30, in <module>
    import tensorflow as tf
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/__init__.py", line 22, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/__init__.py", line 81, in <module>
    from tensorflow.python import keras
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/keras/__init__.py", line 24, in <module>
    from tensorflow.python.keras import activations
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/keras/activations/__init__.py", line 22, in <module>
    from tensorflow.python.keras._impl.keras.activations import elu
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/keras/_impl/keras/__init__.py", line 21, in <module>
    from tensorflow.python.keras._impl.keras import activations
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/keras/_impl/keras/activations.py", line 23, in <module>
    from tensorflow.python.keras._impl.keras import backend as K
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/keras/_impl/keras/backend.py", line 38, in <module>
    from tensorflow.python.layers import base as tf_base_layers
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/layers/base.py", line 25, in <module>
    from tensorflow.python.keras.engine import base_layer
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/keras/engine/__init__.py", line 23, in <module>
    from tensorflow.python.keras.engine.base_layer import InputSpec
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/keras/engine/base_layer.py", line 34, in <module>
    from tensorflow.python.keras import backend
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/keras/backend/__init__.py", line 22, in <module>
    from tensorflow.python.keras._impl.keras.backend import abs
ImportError: cannot import name abs
```

Here's the TFJob spec.

```
apiVersion: kubeflow.org/v1alpha2
kind: TFJob
metadata:
  annotations:
    ksonnet.io/managed: '{"pristine":"H4sIAAAAAAAA/4RTTU/kRhC952fU2T0ej0gAS3NAhCAiAghQcohGVrtd4+lMf6mr7CxC/u+rbg/sLKvd9alUVa9e1evnV5BB/42RtHdQw35ocWv8/wsf+3KspAk7uYIC9tp1UMPzH3/6FgqwyLKTLKF+BSNbNJSiPXnnkBfal8rb4B06hho6tF5wlNphFFUllr8K0q43KPowwFSAkxZ/2je3UZAKj/ZMcAqoEj1vHzEYreRTQJUX+sfHPcYUxblCUFcFMNpgJGMqvIGVd5yZCep/X0HGPgVQDhRL45U0JbXalbxigY7jS/DaMRSQEoedoQAhQvStQbveb5te825om+3gFGvvms4r4qhdnxut79CkNtJWGxk1vzQcpaOtj/YwbBdklJYaQl4f1ZpWEjazNs2sjRDpOZpOx3VPdVkq36EglFHtRNK1XC2rs6panpT52RLADxwG/gEkb0hvyA+PIearG2IMtF4t05fTOEpzyFaHFK+4GShmqlKGkKmamSopCpsC0I1Z+IMXru/vr2+vmouHh9uby4vnm/u75vLx6veru+ebi9snKGCUZkiNJaGKyGWvglARO3SspaFyIIwiJUku/iPvYNoUoK3sE6hXMZn0zUQCP0kbDNJXGvRhqMf348flYiVOl6L/bdmerc5PRKcjvwh5dn6iTuHdw4yOfMzOLCAi+SEqzF402mrOkRt1p+VCeVsmLetqmgoYvRks/uUHx7MDbQofJO++f+QX2o+FaZPOnWfSsa7fTphH518hR3dz45F+ME2bKX+/fAYAAP//AQAA//86vaTXLgQAAA=="}'
  clusterName: ""
  creationTimestamp: 2018-11-06T02:10:06Z
  generation: 1
  labels:
    app.kubernetes.io/deploy-manager: ksonnet
    ksonnet.io/component: demo-trainer-11-05-single-gpu
  name: demo-trainer-11-05-single-gpu
  namespace: kubeflow
  resourceVersion: "667090"
  selfLink: /apis/kubeflow.org/v1alpha2/namespaces/kubeflow/tfjobs/demo-trainer-11-05-single-gpu
  uid: 144ab47a-e169-11e8-b335-42010a8e0fc4
spec:
  cleanPodPolicy: Running
  tfReplicaSpecs:
    Worker:
      replicas: 1
      restartPolicy: Never
      template:
        metadata:
          creationTimestamp: null
        spec:
          containers:
          - args:
            - /usr/local/sbin/t2t-entrypoint
            - t2t-trainer
            - --problem=kf_github_function_docstring
            - --model=kf_similarity_transformer
            - --hparams_set=transformer_base_single_gpu
            - --data_dir=gs://code-search-demo/20181104/data
            - --output_dir=gs://code-search-demo/models/20181105-single-gpu
            - --train_steps=200000
            - --eval_steps=100
            - --t2t_usr_dir=/app/code_search/t2t
            env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /secret/gcp-credentials/user-gcp-sa.json
            image: gcr.io/kubeflow-examples/code-search-gpu:v20181105-v0.2-70-g60b8294-dirty-a894c7
            name: tensorflow
            ports:
            - containerPort: 2222
              name: tfjob-port
            resources:
              limits:
                nvidia.com/gpu: "1"
            volumeMounts:
            - mountPath: /secret/gcp-credentials
              name: gcp-credentials
          volumes:
          - name: gcp-credentials
            secret:
              secretName: user-gcp-sa
status:
  completionTime: 2018-11-06T02:16:07Z
  conditions:
  - lastTransitionTime: 2018-11-06T02:10:06Z
    lastUpdateTime: 2018-11-06T02:10:06Z
    message: TFJob demo-trainer-11-05-single-gpu is created.
    reason: TFJobCreated
    status: "True"
    type: Created
  - lastTransitionTime: 2018-11-06T02:10:06Z
    lastUpdateTime: 2018-11-06T02:16:05Z
    message: TFJob demo-trainer-11-05-single-gpu is running.
    reason: TFJobRunning
    status: "False"
    type: Running
  - lastTransitionTime: 2018-11-06T02:10:06Z
    lastUpdateTime: 2018-11-06T02:16:07Z
    message: TFJob demo-trainer-11-05-single-gpu is failed.
    reason: TFJobFailed
    status: "True"
    type: Failed
  startTime: 2018-11-06T02:16:05Z
  tfReplicaStatuses:
    Chief: {}
    Master: {}
    PS: {}
    Worker: {}

```

**Comment by jlewi** [comment]
Looks like a protobuf issue related to tensorflow/tensorflow#20778.

In #302 we upgraded the protobuf to fix apache_beam.

```
RUN pip install -U protobuf==3.6.1
```

I suspect that might be the problem.

One solution would be to just build different Docker images for Dataflow and training.

Of course the batch prediction job still has a dependency on TensorFlow.

**Comment by jlewi** [comment]
I think the problem is in #302 I started doing pip install requirements.txt
https://github.com/kubeflow/examples/blob/master/code_search/src/requirements.txt

To create a container suitable for running the Dataflow job.  But I think that messes things up because that requirements.txt is specifying a different TF image then is used in the base image.
