### ISSUE TITLE
[code_search] workers keep getting killed when training in distributed mode

### ISSUE THREAD

**Issue by jlewi** [kubeflow/examples#314]
I'm trying to train a model distributed using the transformer_hbase parameters.

I'm using n1-standard-8 with 1 K80s
8 workers with 1 GPU
2 ps

The workers keep dying; but its not clear why.

Last message in the worker logs is:

```
INFO:tensorflow:Done running local_init_op.
```

Below are the TFJob operator logs.

[trainer-logs-1106.txt](https://github.com/kubeflow/examples/files/2553519/trainer-logs-1106.txt)

There's no indication that TFJob controller detects worker as failing. But there is a message about the ps exiting with non-zero exit code

```
Pod: kubeflow.demo-trainer-11-05-dist-gpu-ps-0 exited with code 1
```

The PS are failing with the following stacktrace

```
"Traceback (most recent call last):
  File "/usr/local/bin/t2t-trainer", line 32, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))
  File "/usr/local/bin/t2t-trainer", line 28, in main
    t2t_trainer.main(argv)
  File "/usr/local/lib/python2.7/dist-packages/tensor2tensor/bin/t2t_trainer.py", line 361, in main
    run_std_server()
  File "/usr/local/lib/python2.7/dist-packages/tensor2tensor/bin/t2t_trainer.py", line 355, in run_std_server
    exp.run_std_server()
  File "/usr/local/lib/python2.7/dist-packages/tensor2tensor/utils/trainer_lib.py", line 394, in run_std_server
    task_index=config.task_id)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/server_lib.py", line 147, in __init__
    self._server_def.SerializeToString(), status)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/errors_impl.py", line 519, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InternalError: Job "worker" was not defined in cluster
```

Here's the command to get the TFJob operator logs

```
gcloud --project=${PROJECT} logging read --format="table(timestamp, severity, resource.labels.container_name, jsonPayload.level, jsonPayload.msg)" --freshness=1h      --order asc         "resource.type=\"container\" resource.labels.cluster_name=\"${CLUSTER}\"  resource.labels.pod_id=\"${POD}\"  jsonPayload.job=\"kubeflow.demo-trainer-11-05-dist-gpu\"" > ~/tmp/trainer-logs-1106.txt
```

**Comment by jlewi** [comment]
Looks like there is an issue on distributed training:
kubeflow/examples#208

In that case though its hanging which isn't what we are observing.

**Comment by jlewi** [comment]
The entrypoint script is unsetting TFCONFIG.
https://github.com/kubeflow/examples/blob/aa0061dae211ccfeea50f7bb6e7ca7c23a17ab07/code_search/docker/t2t/t2t-entrypoint.sh#L25

@activatedgeek Do you recall why you did that? Does T2T not understand TF_CONFIG?

**Comment by activatedgeek** [comment]
We were trying to dig into the T2T code and see what parameters were being processed, to figure out what's going wrong with distributed training. To make sure `T2T_CONFIG` doesn't interfere at all with the CLI arguments, we decided to remove it after processing.

**Comment by jlewi** [comment]
Here's the relevant lines of code
https://github.com/tensorflow/tensorflow/blob/r1.8/tensorflow/python/estimator/training.py#L719

Here's a comment explaining how config.master gets set
https://github.com/tensorflow/tensorflow/blob/23c218785eac5bfe737eec4f8081fd0ef8e0684d/tensorflow/python/estimator/run_config.py#L331

And here's the relevant code to actually set it
https://github.com/tensorflow/tensorflow/blob/23c218785eac5bfe737eec4f8081fd0ef8e0684d/tensorflow/python/estimator/run_config.py#L67

**Comment by jlewi** [comment]
Looks to me like t2t_trainer constructs the RunConfig from command line flags rather then respecting TF_CONFIG.
https://github.com/tensorflow/tensor2tensor/blob/master/tensor2tensor/bin/t2t_trainer.py#L232

**Comment by jlewi** [comment]
I went back to using the entrypoint script. 
Workers seem to be running but PS are crashing

```
textPayload:  "Traceback (most recent call last):
  File "/usr/local/bin/t2t-trainer", line 32, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))
  File "/usr/local/bin/t2t-trainer", line 28, in main
    t2t_trainer.main(argv)
  File "/usr/local/lib/python2.7/dist-packages/tensor2tensor/bin/t2t_trainer.py", line 361, in main
    run_std_server()
  File "/usr/local/lib/python2.7/dist-packages/tensor2tensor/bin/t2t_trainer.py", line 355, in run_std_server
    exp.run_std_server()
  File "/usr/local/lib/python2.7/dist-packages/tensor2tensor/utils/trainer_lib.py", line 390, in run_std_server
    config = tf.estimator.RunConfig()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/estimator/run_config.py", line 471, in __init__
    self._init_distributed_setting_from_environment_var(tf_config)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/estimator/run_config.py", line 487, in _init_distributed_setting_from_environment_var
    self._cluster_spec, task_env, TaskType.CHIEF)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/estimator/run_config.py", line 155, in _validate_task_type_and_task_id
    chief_task_type)
ValueError: If "cluster" is set in TF_CONFIG, it must have one "chief" node.
```

**Comment by jlewi** [comment]
Looks like TF_CONFIG just uses "chief" as the task type.
https://github.com/tensorflow/tensorflow/blob/r1.8/tensorflow/python/estimator/run_config.py#L287

**Comment by jlewi** [comment]
Here's what we did for T2T distributed for GitHub issue summarization.
https://github.com/kubeflow/examples/blob/d2c5e949e59bc67afa359f38ae7ed4edefeecbef/github_issue_summarization/ks-kubeflow/components/tensor2tensor-v1alpha2.jsonnet

Looks like we just had the same config as for the workers but with a different value for "--worker_job".

**Comment by jlewi** [comment]
So I'm hitting two problems

1. Can't start PS that gives me error above https://github.com/kubeflow/examples/issues/314#issuecomment-436356931

1. Without PS training gets stuck after Graph finalized which looks like #208; I see the error

```
INFO:tensorflow:schedule=continuous_train_and_eval
INFO:tensorflow:worker_gpu=1
INFO:tensorflow:sync=False
WARNING:tensorflow:Schedule=continuous_train_and_eval. Assuming that training is running on a single machine.
INFO:tensorflow:datashard_devices: ['gpu:0']
INFO:tensorflow:caching_devices: None
INFO:tensorflow:ps_devices: ['gpu:0']
```

**Comment by jlewi** [comment]
Closing this issue and consolidating on #208
