### ISSUE TITLE
[code search] preprocess failed: Can't find model 'en' 

### ISSUE THREAD

**Issue by IronPan** [kubeflow/examples#321]
I was following the notebook instruction and got this error when sending preprocess dataflow job

/root/.local/lib/python2.7/site-packages/scipy/spatial/__init__.py:96: ImportWarning: Not importing directory '/root/.local/lib/python2.7/site-packages/scipy/spatial/qhull': missing __init__.py
  from .qhull import *
/root/.local/lib/python2.7/site-packages/scipy/optimize/_minimize.py:37: ImportWarning: Not importing directory '/root/.local/lib/python2.7/site-packages/scipy/optimize/lbfgsb': missing __init__.py
  from .lbfgsb import _minimize_lbfgsb
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/local/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/examples/code_search/src/code_search/dataflow/cli/preprocess_github_dataset.py", line 7, in <module>
    import code_search.dataflow.transforms.github_dataset as github_dataset
  File "code_search/dataflow/transforms/github_dataset.py", line 5, in <module>
    import code_search.dataflow.do_fns.github_dataset as gh_do_fns
  File "code_search/dataflow/do_fns/github_dataset.py", line 6, in <module>
    import code_search.dataflow.utils as utils
  File "code_search/dataflow/utils.py", line 9, in <module>
    en = spacy.load('en')
  File "/root/.local/lib/python2.7/site-packages/spacy/__init__.py", line 21, in load
    return util.load_model(name, **overrides)
  File "/root/.local/lib/python2.7/site-packages/spacy/util.py", line 119, in load_model
    raise IOError(Errors.E050.format(name=name))
IOError: [E050] Can't find model 'en'. It doesn't seem to be a shortcut link, a Python package or a valid path to a data directory.

**Comment by IronPan** [comment]
It looks like I need to run following to install the package 
```
! python2 -m spacy download en  --user
```
[Ref](https://github.com/fastai/fastai/issues/632)

**Comment by jlewi** [comment]
@IronPan Where did you run this?

The command above does need to be run in order to have the en package installed.

If you are using the Direct Dataflow pipeline runner then you will need to run the above command to have the package installed on your machine.

However, if you run it using the Dataflow runner the package should be installed on all the workers automatically.

That's because our setup.py file includes custom commands to install it.
https://github.com/kubeflow/examples/blob/c6ff5dbef895c5a4b7e14df150aa33ce2c98e1cd/code_search/src/setup.py#L12
