### ISSUE TITLE
[Code Search] Export Tensorflow Model Failed to run

### ISSUE THREAD

**Issue by IronPan** [kubeflow/examples#329]
By following the notebook, here is what I got
```
Running command: 't2t-exporter --tmp_dir=/tmp --t2t_usr_dir=/app/code_search/t2t --problem=kf_github_function_docstring --data_dir=gs://code-search-demo/20181104/data --output_dir=gs://code-search-demo/models/20181105-tinyparams --model=kf_similarity_transformer --hparams_set=transformer_tiny'
/usr/local/lib/python2.7/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
INFO:tensorflow:Importing user module t2t from path /app/code_search
Traceback (most recent call last):
  File "/usr/local/bin/t2t-exporter", line 16, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))
  File "/usr/local/bin/t2t-exporter", line 12, in main
    export.main(argv)
  File "/usr/local/lib/python2.7/dist-packages/tensor2tensor/serving/export.py", line 54, in main
    hparams = create_hparams()
  File "/usr/local/lib/python2.7/dist-packages/tensor2tensor/serving/export.py", line 44, in create_hparams
    problem_name=FLAGS.problem)
  File "/usr/local/lib/python2.7/dist-packages/tensor2tensor/utils/trainer_lib.py", line 92, in create_hparams
    add_problem_hparams(hparams, problem_name)
  File "/usr/local/lib/python2.7/dist-packages/tensor2tensor/utils/trainer_lib.py", line 535, in add_problem_hparams
    problem = registry.problem(problem_name)
  File "/usr/local/lib/python2.7/dist-packages/tensor2tensor/utils/registry.py", line 277, in problem
    raise LookupError(error_msg)
LookupError: kf_github_function_docstring not in the set of supported problems:
  * algorithmic_addition_binary40
  * algorithmic_addition_decimal40
  * algorithmic_cipher_shift200
  * algorithmic_cipher_shift5
....
```

**Comment by IronPan** [comment]
It might be fixed by https://github.com/kubeflow/examples/pull/320/files#diff-ef12175c2c7d524cf2281d3c878fbedbR38
