### ISSUE TITLE
[code_search] Create function embedding failed - tensorflow no matching distribution

### ISSUE THREAD

**Issue by IronPan** [kubeflow/examples#357]
create function embedding job failed with following error. The job is created by running 

ks apply cs_demo -c submit-code-embeddings-job

```
INFO|2018-11-25T07:31:36|/usr/local/lib/python2.7/site-packages/apache_beam/runners/portability/stager.py|410| Executing command: ['/usr/local/bin/python2', '-m', 'pip', 'download', '--dest', '/tmp/dataflow-requirements-cache', '-r', 'requirements.dataflow.txt', '--exists-action', 'i', '--no-binary', ':all:']
Collecting astor~=0.7.0 (from -r requirements.dataflow.txt (line 4))
  Downloading https://files.pythonhosted.org/packages/99/80/f9482277c919d28bebd85813c0a70117214149a96b08981b72b63240b84c/astor-0.7.1.tar.gz
  Saved /tmp/dataflow-requirements-cache/astor-0.7.1.tar.gz
Collecting apache-beam[gcp]~=2.8.0 (from -r requirements.dataflow.txt (line 5))
  Downloading https://files.pythonhosted.org/packages/81/ea/11cec69a659af024f7f37e928ff533ad5e30b7a519d9982e2bb5b81fcb52/apache-beam-2.8.0.zip (1.2MB)
  Saved /tmp/dataflow-requirements-cache/apache-beam-2.8.0.zip
Collecting nltk~=3.3.0 (from -r requirements.dataflow.txt (line 6))
  Using cached https://files.pythonhosted.org/packages/50/09/3b1755d528ad9156ee7243d52aa5cd2b809ef053a0f31b53d92853dd653a/nltk-3.3.0.zip
  Saved /tmp/dataflow-requirements-cache/nltk-3.3.0.zip
Collecting oauth2client~=4.1.0 (from -r requirements.dataflow.txt (line 7))
  Downloading https://files.pythonhosted.org/packages/a6/7b/17244b1083e8e604bf154cf9b716aecd6388acd656dd01893d0d244c94d9/oauth2client-4.1.3.tar.gz (155kB)
  Saved /tmp/dataflow-requirements-cache/oauth2client-4.1.3.tar.gz
Collecting spacy~=2.0.0 (from -r requirements.dataflow.txt (line 8))
  Downloading https://files.pythonhosted.org/packages/3a/86/e3c4bc5fde980387c817e57b870ad6b31df507d88df1ea69263ef4c939a2/spacy-2.0.16.tar.gz (23.0MB)
  Saved /tmp/dataflow-requirements-cache/spacy-2.0.16.tar.gz
Collecting tensor2tensor~=1.9.0 (from -r requirements.dataflow.txt (line 9))
  Downloading https://files.pythonhosted.org/packages/8a/8c/fbc927abb03e3298205fbea972b6c5b2e451972461e3c7e03d0126ba7723/tensor2tensor-1.9.0.tar.gz (761kB)
  Saved /tmp/dataflow-requirements-cache/tensor2tensor-1.9.0.tar.gz
Collecting tensorflow~=1.11.0 (from -r requirements.dataflow.txt (line 10))
  Could not find a version that satisfies the requirement tensorflow~=1.11.0 (from -r requirements.dataflow.txt (line 10)) (from versions: )
No matching distribution found for tensorflow~=1.11.0 (from -r requirements.dataflow.txt (line 10))
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/local/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/src/code_search/dataflow/cli/create_function_embeddings.py", line 63, in <module>
    create_function_embeddings()
  File "/src/code_search/dataflow/cli/create_function_embeddings.py", line 50, in create_function_embeddings
    result = pipeline.run()
  File "/usr/local/lib/python2.7/site-packages/apache_beam/pipeline.py", line 416, in run
    return self.runner.run_pipeline(self)
  File "/usr/local/lib/python2.7/site-packages/apache_beam/runners/dataflow/dataflow_runner.py", line 389, in run_pipeline
    self.dataflow_client.create_job(self.job), self)
  File "/usr/local/lib/python2.7/site-packages/apache_beam/utils/retry.py", line 184, in wrapper
    return fun(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/apache_beam/runners/dataflow/internal/apiclient.py", line 490, in create_job
    self.create_job_description(job)
  File "/usr/local/lib/python2.7/site-packages/apache_beam/runners/dataflow/internal/apiclient.py", line 519, in create_job_description
    resources = self._stage_resources(job.options)
  File "/usr/local/lib/python2.7/site-packages/apache_beam/runners/dataflow/internal/apiclient.py", line 452, in _stage_resources
    staging_location=google_cloud_options.staging_location)
  File "/usr/local/lib/python2.7/site-packages/apache_beam/runners/portability/stager.py", line 161, in stage_job_resources
    requirements_cache_path)
  File "/usr/local/lib/python2.7/site-packages/apache_beam/runners/portability/stager.py", line 411, in _populate_requirements_cache
    processes.check_call(cmd_args)
  File "/usr/local/lib/python2.7/site-packages/apache_beam/utils/processes.py", line 46, in check_call
    return subprocess.check_call(*args, **kwargs)
  File "/usr/local/lib/python2.7/subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/local/bin/python2', '-m', 'pip', 'download', '--dest', '/tmp/dataflow-requirements-cache', '-r', 'requirements.dataflow.txt', '--exists-action', 'i', '--no-binary', ':all:']' returned non-zero exit status 1
```

**Comment by jlewi** [comment]
I haven't encountered this issue.

Which version of Apache Beam are you using.
Each version of Apache Beam i think is test with a specific version of TF for things like TF.transform.
https://github.com/tensorflow/transform

Looking in project code-search-demo; I see successful runs using Apache Beam 2.8.0 which uses TF 1.11 which I believe is what the job should be configured to use.

It looks like the most recent versions of the Dataflow job are the ones submitted by your pipeline based on the naming
compute-function-embeddings-20181111-005956

It looks like these are using Apache Beam 2.6.

Did you change the Docker image used by submit-code-embeddings-job?  Or did you submit the job from the pipeline?

Based on the requirements file
https://github.com/kubeflow/examples/blob/master/code_search/src/requirements.dataflow.txt

We should be using Apache Beam 2.8.0 and TF 1.11

**Comment by jlewi** [comment]
I tried rerunning the job and I'm getting the same error.
This is very weird as I'm pretty sure it was working before. 

It looks like Dataflow is trying to download the dependencies locally as part of the job submission process; not sure why that would break suddenly.

**Comment by jlewi** [comment]
I can repo it by running the same command that Dataflow is running in the container

```
/usr/local/bin/python2 -m pip download --dest /tmp/dataflow-requirements-cache -r requirements.dataflow.txt --exists-action i --no-binary :all:
```

**Comment by jlewi** [comment]
If we drop `no binary` the command succeeeds; e.g.

```
/usr/local/bin/python2 -m pip download --dest /tmp/dataflow-requirements-cache -r requirements.dataflow.txt --exists-action i
```

**Comment by jlewi** [comment]
According to the docs --no-binary might prevent fetching binary packages.
https://pip.pypa.io/en/stable/reference/pip_download/

I suspect Dataflow doesn't want binary packages because the target system might be different from the system uploading the packages.

I think the solution here might be to remove TensorFlow from the requirements file. I think Dataflow might already include TensorFlow in the worker images and we should probably just try to use that version (for 2.8.0 it should be TF 1.11 so there should be no mismatch).

**Comment by jlewi** [comment]
Here's the list of packages already installed on the workers
https://cloud.google.com/dataflow/docs/concepts/sdk-worker-dependencies#sdk-for-python

So we should be able to remove tensorflow.

**Comment by IronPan** [comment]
this is resolved after i removed the tensorflow from requirement.txt
