### ISSUE TITLE
Distributed MNIST w/ minio met 'NotFoundError: /tmp/....; No such file or directory'

### ISSUE THREAD

**Issue by NKUCodingCat** [kubeflow/examples#521]
Hey guys, I am trying to tran MNIST sample and use minio to replace S3, and I got 

```
root@kube-worker:~/examples/mnist/ks_app# kubectl logs mnist-train-dist-chief-0
/usr/local/lib/python2.7/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
INFO:tensorflow:TF_CONFIG {"cluster":{"chief":["mnist-train-dist-chief-0.default.svc:2222"],"ps":["mnist-train-dist-ps-0.default.svc:2222"],"worker":["mnist-train-dist-worker-0.default.svc:2222","mnist-train-dist-worker-1.default.svc:2222"]},"task":{"type":"chief","index":0},"environment":"cloud"}
INFO:tensorflow:cluster={u'ps': [u'mnist-train-dist-ps-0.default.svc:2222'], u'chief': [u'mnist-train-dist-chief-0.default.svc:2222'], u'worker': [u'mnist-train-dist-worker-0.default.svc:2222', u'mnist-train-dist-worker-1.default.svc:2222']} job_name=chief task_index=0
INFO:tensorflow:Will export model
WARNING:tensorflow:From /usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/datasets/base.py:198: retry (from tensorflow.contrib.learn.python.learn.datasets.base) is deprecated and will be removed in a future version.
Instructions for updating:
Use the retry module or similar alternatives.
WARNING:tensorflow:From /opt/model.py:147: load_mnist (from tensorflow.contrib.learn.python.learn.datasets.mnist) is deprecated and will be removed in a future version.
Instructions for updating:
Please use alternatives such as official/mnist/dataset.py from tensorflow/models.
WARNING:tensorflow:From /usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/datasets/mnist.py:300: read_data_sets (from tensorflow.contrib.learn.python.learn.datasets.mnist) is deprecated and will be removed in a future version.
Instructions for updating:
Please use alternatives such as official/mnist/dataset.py from tensorflow/models.
WARNING:tensorflow:From /usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/datasets/mnist.py:260: maybe_download (from tensorflow.contrib.learn.python.learn.datasets.base) is deprecated and will be removed in a future version.
Instructions for updating:
Please write your own downloading logic.
WARNING:tensorflow:From /usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/datasets/base.py:219: wrapped_fn (from tensorflow.contrib.learn.python.learn.datasets.base) is deprecated and will be removed in a future version.
Instructions for updating:
Please use urllib or similar directly.
WARNING:tensorflow:From /usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/datasets/mnist.py:262: extract_images (from tensorflow.contrib.learn.python.learn.datasets.mnist) is deprecated and will be removed in a future version.
Instructions for updating:
Please use tf.data to implement this functionality.
WARNING:tensorflow:From /usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/datasets/mnist.py:267: extract_labels (from tensorflow.contrib.learn.python.learn.datasets.mnist) is deprecated and will be removed in a future version.
Instructions for updating:
Please use tf.data to implement this functionality.
WARNING:tensorflow:From /usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/datasets/mnist.py:290: __init__ (from tensorflow.contrib.learn.python.learn.datasets.mnist) is deprecated and will be removed in a future version.
Instructions for updating:
Please use alternatives such as official/mnist/dataset.py from tensorflow/models.
INFO:tensorflow:TF_CONFIG environment variable: {u'environment': u'cloud', u'cluster': {u'ps': [u'mnist-train-dist-ps-0.default.svc:2222'], u'chief': [u'mnist-train-dist-chief-0.default.svc:2222'], u'worker': [u'mnist-train-dist-worker-0.default.svc:2222', u'mnist-train-dist-worker-1.default.svc:2222']}, u'task': {u'index': 0, u'type': u'chief'}}
WARNING:tensorflow:Using temporary folder as model directory: /tmp/tmpKx886b
INFO:tensorflow:Using config: {'_save_checkpoints_secs': None, '_session_config': None, '_keep_checkpoint_max': 5, '_task_type': u'chief', '_global_id_in_cluster': 0, '_is_chief': True, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7f82a045d790>, '_evaluation_master': '', '_save_checkpoints_steps': 1000, '_keep_checkpoint_every_n_hours': 10000, '_service': None, '_num_ps_replicas': 1, '_tf_random_seed': None, '_master': u'grpc://mnist-train-dist-chief-0.default.svc:2222', '_num_worker_replicas': 3, '_task_id': 0, '_log_step_count_steps': 100, '_model_dir': '/tmp/tmpKx886b', '_save_summary_steps': 100}
INFO:tensorflow:Start Tensorflow server.
2019-03-01 04:07:53.102416: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-03-01 04:07:53.104488: I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:215] Initialize GrpcChannelCache for job chief -> {0 -> localhost:2222}
2019-03-01 04:07:53.104512: I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:215] Initialize GrpcChannelCache for job ps -> {0 -> mnist-train-dist-ps-0.default.svc:2222}
2019-03-01 04:07:53.104520: I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:215] Initialize GrpcChannelCache for job worker -> {0 -> mnist-train-dist-worker-0.default.svc:2222, 1 -> mnist-train-dist-worker-1.default.svc:2222}
2019-03-01 04:07:53.107085: I tensorflow/core/distributed_runtime/rpc/grpc_server_lib.cc:333] Started server with target: grpc://localhost:2222
INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Graph was finalized.
2019-03-01 04:08:03.679364: I tensorflow/core/distributed_runtime/master.cc:221] CreateSession still waiting for response from worker: /job:ps/replica:0/task:0
2019-03-01 04:08:13.679568: I tensorflow/core/distributed_runtime/master.cc:221] CreateSession still waiting for response from worker: /job:ps/replica:0/task:0
2019-03-01 04:08:23.679740: I tensorflow/core/distributed_runtime/master.cc:221] CreateSession still waiting for response from worker: /job:ps/replica:0/task:0
2019-03-01 04:08:28.692347: E tensorflow/core/distributed_runtime/master.cc:269] Master init: Unavailable: OS Error
INFO:tensorflow:An error was raised while a session was being created. This may be due to a preemption of a connected worker or parameter server. A new session will be created. Error: OS Error
INFO:tensorflow:Graph was finalized.
2019-03-01 04:08:28.741756: I tensorflow/core/distributed_runtime/master_session.cc:1024] Start master session ab1f1f493d4195d8 with config: allow_soft_placement: true
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Saving checkpoints for 1 into /tmp/tmpKx886b/model.ckpt.
Successfully downloaded train-images-idx3-ubyte.gz 9912422 bytes.
Extracting /tmp/data/train-images-idx3-ubyte.gz
Successfully downloaded train-labels-idx1-ubyte.gz 28881 bytes.
Extracting /tmp/data/train-labels-idx1-ubyte.gz
Successfully downloaded t10k-images-idx3-ubyte.gz 1648877 bytes.
Extracting /tmp/data/t10k-images-idx3-ubyte.gz
Successfully downloaded t10k-labels-idx1-ubyte.gz 4542 bytes.
Extracting /tmp/data/t10k-labels-idx1-ubyte.gz
Train and evaluate
Traceback (most recent call last):
  File "/opt/model.py", line 204, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))
  File "/opt/model.py", line 195, in main
    tf.estimator.train_and_evaluate(classifier, train_spec, eval_spec)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/estimator/training.py", line 439, in train_and_evaluate
    executor.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/estimator/training.py", line 546, in run
    getattr(self, task_to_run)()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/estimator/training.py", line 551, in run_chief
    return self._start_distributed_training()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/estimator/training.py", line 739, in _start_distributed_training
    saving_listeners=saving_listeners)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/estimator/estimator.py", line 355, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/estimator/estimator.py", line 903, in _train_model
    _, loss = mon_sess.run([estimator_spec.train_op, estimator_spec.loss])
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/monitored_session.py", line 546, in run
    run_metadata=run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/monitored_session.py", line 1022, in run
    run_metadata=run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/monitored_session.py", line 1113, in run
    raise six.reraise(*original_exc_info)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/monitored_session.py", line 1098, in run
    return self._sess.run(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/monitored_session.py", line 1178, in run
    run_metadata=run_metadata))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/basic_session_run_hooks.py", line 458, in after_run
    self._save(run_context.session, global_step)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/basic_session_run_hooks.py", line 474, in _save
    self._get_saver().save(session, self._save_path, global_step=step)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 1693, in save
    raise exc
tensorflow.python.framework.errors_impl.NotFoundError: /tmp/tmpKx886b/model.ckpt-1_temp_e4f231119cde4659adb7a3bbcf58f8a8; No such file or directory
	 [[Node: save/SaveV2 = SaveV2[dtypes=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_INT64], _device="/job:ps/replica:0/task:0/device:CPU:0"](save/ShardedFilename, save/SaveV2/tensor_names, save/SaveV2/shape_and_slices, conv_layer1/conv2d/bias, conv_layer1/conv2d/kernel, conv_layer2/conv2d/bias, conv_layer2/conv2d/kernel, dense/bias, dense/kernel, dense_1/bias, dense_1/kernel, global_step)]]
	 [[Node: save/Identity_S99 = _HostRecv[client_terminated=false, recv_device="/job:chief/replica:0/task:0/device:CPU:0", send_device="/job:ps/replica:0/task:0/device:CPU:0", send_device_incarnation=-8264624975981376499, tensor_name="edge_45_save/Identity", tensor_type=DT_STRING, _device="/job:chief/replica:0/task:0/device:CPU:0"]()]]

Caused by op u'save/SaveV2', defined at:
  File "/opt/model.py", line 204, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))
  File "/opt/model.py", line 195, in main
    tf.estimator.train_and_evaluate(classifier, train_spec, eval_spec)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/estimator/training.py", line 439, in train_and_evaluate
    executor.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/estimator/training.py", line 546, in run
    getattr(self, task_to_run)()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/estimator/training.py", line 551, in run_chief
    return self._start_distributed_training()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/estimator/training.py", line 739, in _start_distributed_training
    saving_listeners=saving_listeners)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/estimator/estimator.py", line 355, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/estimator/estimator.py", line 900, in _train_model
    log_step_count_steps=self._config.log_step_count_steps) as mon_sess:
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/monitored_session.py", line 384, in MonitoredTrainingSession
    stop_grace_period_secs=stop_grace_period_secs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/monitored_session.py", line 795, in __init__
    stop_grace_period_secs=stop_grace_period_secs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/monitored_session.py", line 518, in __init__
    self._sess = _RecoverableSession(self._coordinated_creator)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/monitored_session.py", line 981, in __init__
    _WrappedSession.__init__(self, self._create_session())
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/monitored_session.py", line 986, in _create_session
    return self._sess_creator.create_session()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/monitored_session.py", line 675, in create_session
    self.tf_sess = self._session_creator.create_session()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/monitored_session.py", line 437, in create_session
    self._scaffold.finalize()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/monitored_session.py", line 214, in finalize
    self._saver.build()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 1320, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 1357, in _build
    build_save=build_save, build_restore=build_restore)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 800, in _build_internal
    save_tensor = self._AddShardedSaveOps(filename_tensor, per_device)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 411, in _AddShardedSaveOps
    return self._AddShardedSaveOpsForV2(filename_tensor, per_device)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 385, in _AddShardedSaveOpsForV2
    sharded_saves.append(self._AddSaveOps(sharded_filename, saveables))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 326, in _AddSaveOps
    save = self.save_op(filename_tensor, saveables)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 242, in save_op
    tensors)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_io_ops.py", line 1680, in save_v2
    shape_and_slices=shape_and_slices, tensors=tensors, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 3290, in create_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1654, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

NotFoundError (see above for traceback): /tmp/tmpKx886b/model.ckpt-1_temp_e4f231119cde4659adb7a3bbcf58f8a8; No such file or directory
	 [[Node: save/SaveV2 = SaveV2[dtypes=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_INT64], _device="/job:ps/replica:0/task:0/device:CPU:0"](save/ShardedFilename, save/SaveV2/tensor_names, save/SaveV2/shape_and_slices, conv_layer1/conv2d/bias, conv_layer1/conv2d/kernel, conv_layer2/conv2d/bias, conv_layer2/conv2d/kernel, dense/bias, dense/kernel, dense_1/bias, dense_1/kernel, global_step)]]
	 [[Node: save/Identity_S99 = _HostRecv[client_terminated=false, recv_device="/job:chief/replica:0/task:0/device:CPU:0", send_device="/job:ps/replica:0/task:0/device:CPU:0", send_device_incarnation=-8264624975981376499, tensor_name="edge_45_save/Identity", tensor_type=DT_STRING, _device="/job:chief/replica:0/task:0/device:CPU:0"]()]]
```

and the task file

```
root@kube-worker:~/examples/mnist/ks_app# ks show ${KSENV} -c train
---
apiVersion: kubeflow.org/v1beta1
kind: TFJob
metadata:
  labels:
    ksonnet.io/component: train
  name: mnist-train-dist
  namespace: default
spec:
  tfReplicaSpecs:
    Chief:
      replicas: 1
      template:
        spec:
          containers:
          - args:
            - --tf-model-dir=MODEL-Fri-19Mar01-040028
            - --tf-export-dir=EXPORT-Fri-19Mar01-040028
            - --tf-train-steps=200
            - --tf-batch-size=100
            - --tf-learning-rate=0.01
            command:
            - /usr/bin/python
            - /opt/model.py
            env:
            - name: S3_ENDPOINT
              value: 10.193.27.77:9000
            - name: AWS_ENDPOINT_URL
              value: http://10.193.27.77:9000
            - name: AWS_REGION
              value: us-west-2
            - name: BUCKET_NAME
              value: mybucket
            - name: S3_USE_HTTPS
              value: "0"
            - name: S3_VERIFY_SSL
              value: "0"
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  key: awsAccessKeyID
                  name: aws-creds
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  key: awsSecretAccessKey
                  name: aws-creds
            image: gcr.io/kubeflow-examples/mnist/model:v20190111-v0.2-148-g313770f
            name: tensorflow
            volumeMounts: []
            workingDir: /opt
          restartPolicy: OnFailure
          volumes: []
    Ps:
      replicas: 1
      template:
        spec:
          containers:
          - args:
            - --tf-model-dir=MODEL-Fri-19Mar01-040028
            - --tf-export-dir=EXPORT-Fri-19Mar01-040028
            - --tf-train-steps=200
            - --tf-batch-size=100
            - --tf-learning-rate=0.01
            command:
            - /usr/bin/python
            - /opt/model.py
            env:
            - name: S3_ENDPOINT
              value: 10.193.27.77:9000
            - name: AWS_ENDPOINT_URL
              value: http://10.193.27.77:9000
            - name: AWS_REGION
              value: us-west-2
            - name: BUCKET_NAME
              value: mybucket
            - name: S3_USE_HTTPS
              value: "0"
            - name: S3_VERIFY_SSL
              value: "0"
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  key: awsAccessKeyID
                  name: aws-creds
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  key: awsSecretAccessKey
                  name: aws-creds
            image: gcr.io/kubeflow-examples/mnist/model:v20190111-v0.2-148-g313770f
            name: tensorflow
            volumeMounts: []
            workingDir: /opt
          restartPolicy: OnFailure
          volumes: []
    Worker:
      replicas: 2
      template:
        spec:
          containers:
          - args:
            - --tf-model-dir=MODEL-Fri-19Mar01-040028
            - --tf-export-dir=EXPORT-Fri-19Mar01-040028
            - --tf-train-steps=200
            - --tf-batch-size=100
            - --tf-learning-rate=0.01
            command:
            - /usr/bin/python
            - /opt/model.py
            env:
            - name: S3_ENDPOINT
              value: 10.193.27.77:9000
            - name: AWS_ENDPOINT_URL
              value: http://10.193.27.77:9000
            - name: AWS_REGION
              value: us-west-2
            - name: BUCKET_NAME
              value: mybucket
            - name: S3_USE_HTTPS
              value: "0"
            - name: S3_VERIFY_SSL
              value: "0"
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  key: awsAccessKeyID
                  name: aws-creds
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  key: awsSecretAccessKey
                  name: aws-creds
            image: gcr.io/kubeflow-examples/mnist/model:v20190111-v0.2-148-g313770f
            name: tensorflow
            volumeMounts: []
            workingDir: /opt
          restartPolicy: OnFailure
          volumes: []
```

It seems like file syncing problem or some file system error? Is there any solution about it?

**Comment by NKUCodingCat** [comment]
Fine... I know how this example works.... and I need to send files to S3...

**Comment by sh0gg0th** [comment]
@NKUCodingCat how did you fix it? thanks!

**Comment by NKUCodingCat** [comment]
@sh0gg0th I paste my own yaml file here to help you check for it, it is basically caused by the misconfig of your S3, 

The key problem is `tf-model-dir=s3://mybucket/job-Mar22`, which should be the full uri of S3, the guidance of kubeflow is not so clear here which will cause misunderstanding 

```
apiVersion: kubeflow.org/v1beta1
kind: TFJob
metadata:
  annotations:
    ksonnet.io/managed: '{"pristine":"H4sIAAAAAAAA/+yTQW/iPhDF7/+PMeeEJKB/tRupB5aGXZaWIkJbVVUVOc4A3iR2ZE/KslW++8qhoLRStT32QE7WzHt+Y8e/Z2CVuEVthJIQQl6nuCrUtqf02nsKUiQWgAO5kBmEsBz/VCk4UCKxjBGD8BkKlmJh7Co3SkqknlAeV2WlJEqCEEgzIaFxQLISIYRSCkNuW3UzYQj2HVMxbtsZrlhdkDWYCrndmFYLrArBWVwhb6NGG4Eru9D7hoEwcICwrApGaBsHL1eSmJCoDYQPz8D02i7AdWnllirDws2EPjeD0PPKXVrzHMn7pVL3iul+H5y9EH9XStNHlPtjGcLKnAe+7x/qKSO+cY34g7Z8qBbItBRy7WpGeB70/NdfgK7/Pzw6wFVZMvsHHsCrjfZSIb1qRxslwQFPVeS1R+lVO6tG+dSe9eW+40ESzS7m15PZEhx4YkVtq4HfC86CXnDW7/X74Vc7auMcPcO7+GhKbhaXHeOGqAo979/+RfR9cj3rOGvjIjPkBl3lt5vRNFoms+FV1JEeLrirjAfJTRwlP5bLedyR+m80t9FiMr5P4vjyPZEdbjgaRXGcTKP7ZHJxEI61Ktu3g1wjTXG32D+yHHcQAtuaIedozBR3redlO7Y1LteYGWiaNylxNFpEy07Yh5PitnHMeyft0QFRsnWLjeI5asuezGuuMiHXnJGXf1klLXAJ4RE1CyVKo7Ql3Y6kirrEK1VLsnA8OrBVOhdyfSE0hO0DA5ul0RDTNFeF4HbOazlmoqg1Hvdo7fYaYG5OeJ7wPOH5SfG8UzpH/RrRwQnRE6InRD8Hok3T/PcXAAD//wEAAP//yWMxoJwLAAA="}'
  creationTimestamp: "2019-03-25T02:12:08Z"
  generation: 12
  labels:
    app.kubernetes.io/deploy-manager: ksonnet
    ksonnet.io/component: train
  name: mnist-train-dist
  namespace: default
  resourceVersion: "739170"
  selfLink: /apis/kubeflow.org/v1beta1/namespaces/default/tfjobs/mnist-train-dist
  uid: 6463dc82-4ea3-11e9-87a8-02000dffeaa4
spec:
  cleanPodPolicy: Running
  tfReplicaSpecs:
    Chief:
      replicas: 1
      restartPolicy: Never
      template:
        metadata:
          creationTimestamp: null
        spec:
          containers:
          - args:
            - --tf-model-dir=s3://mybucket/job-Mar22
            - --tf-export-dir=s3://mybucket/job-Mar22
            - --tf-train-steps=1000
            - --tf-batch-size=100
            - --tf-learning-rate=1.0000000000000001e-05
            command:
            - /usr/bin/python
            - /opt/model.py
            env:
            - name: S3_ENDPOINT
              value: 10.161.162.22:9000
            - name: AWS_ENDPOINT_URL
              value: http://10.161.162.22:9000
            - name: AWS_REGION
              value: us-east-1
            - name: BUCKET_NAME
              value: mybucket
            - name: S3_USE_HTTPS
              value: "0"
            - name: S3_VERIFY_SSL
              value: "0"
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  key: awsAccessKeyID
                  name: aws-creds
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  key: awsSecretAccessKey
                  name: aws-creds
            image: docker.io/nkucodingcat/k8f_mnist_test
            name: tensorflow
            ports:
            - containerPort: 2222
              name: tfjob-port
            resources: {}
            workingDir: /opt
          restartPolicy: OnFailure
    PS:
      replicas: 1
      restartPolicy: Never
      template:
        metadata:
          creationTimestamp: null
        spec:
          containers:
          - args:
            - --tf-model-dir=s3://mybucket/job-Mar22
            - --tf-export-dir=s3://mybucket/job-Mar22
            - --tf-train-steps=1000
            - --tf-batch-size=100
            - --tf-learning-rate=1.0000000000000001e-05
            command:
            - /usr/bin/python
            - /opt/model.py
            env:
            - name: S3_ENDPOINT
              value: 10.161.162.22:9000
            - name: AWS_ENDPOINT_URL
              value: http://10.161.162.22:9000
            - name: AWS_REGION
              value: us-east-1
            - name: BUCKET_NAME
              value: mybucket
            - name: S3_USE_HTTPS
              value: "0"
            - name: S3_VERIFY_SSL
              value: "0"
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  key: awsAccessKeyID
                  name: aws-creds
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  key: awsSecretAccessKey
                  name: aws-creds
            image: docker.io/nkucodingcat/k8f_mnist_test
            name: tensorflow
            ports:
            - containerPort: 2222
              name: tfjob-port
            resources: {}
            workingDir: /opt
          restartPolicy: OnFailure
    Worker:
      replicas: 3
      restartPolicy: Never
      template:
        metadata:
          creationTimestamp: null
        spec:
          containers:
          - args:
            - --tf-model-dir=s3://mybucket/job-Mar22
            - --tf-export-dir=s3://mybucket/job-Mar22
            - --tf-train-steps=1000
            - --tf-batch-size=100
            - --tf-learning-rate=1.0000000000000001e-05
            command:
            - /usr/bin/python
            - /opt/model.py
            env:
            - name: S3_ENDPOINT
              value: 10.161.162.22:9000
            - name: AWS_ENDPOINT_URL
              value: http://10.161.162.22:9000
            - name: AWS_REGION
              value: us-east-1
            - name: BUCKET_NAME
              value: mybucket
            - name: S3_USE_HTTPS
              value: "0"
            - name: S3_VERIFY_SSL
              value: "0"
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  key: awsAccessKeyID
                  name: aws-creds
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  key: awsSecretAccessKey
                  name: aws-creds
            image: docker.io/nkucodingcat/k8f_mnist_test
            name: tensorflow
            ports:
            - containerPort: 2222
              name: tfjob-port
            resources: {}
            workingDir: /opt
          restartPolicy: OnFailure
status:
  completionTime: "2019-03-25T02:12:41Z"
  conditions:
  - lastTransitionTime: "2019-03-25T02:12:08Z"
    lastUpdateTime: "2019-03-25T02:12:08Z"
    message: TFJob mnist-train-dist is created.
    reason: TFJobCreated
    status: "True"
    type: Created
  - lastTransitionTime: "2019-03-25T02:12:12Z"
    lastUpdateTime: "2019-03-25T02:12:12Z"
    message: TFJob mnist-train-dist is running.
    reason: TFJobRunning
    status: "False"
    type: Running
  - lastTransitionTime: "2019-03-25T02:12:41Z"
    lastUpdateTime: "2019-03-25T02:12:41Z"
    message: TFJob mnist-train-dist is successfully completed.
    reason: TFJobSucceeded
    status: "True"
    type: Succeeded
  replicaStatuses:
    Chief: {}
    Master: {}
    PS: {}
    Worker: {}
  startTime: "2019-03-25T02:12:11Z"
```
