### ISSUE TITLE
Upgrade tfjob version in the mnist example

### ISSUE THREAD

**Issue by jinchihe** [kubeflow/examples#567]
I installed last `kubeflow` and found the CRD tfjobs version has been upgraded.

```bash
#kubectl describe crd tfjobs.kubeflow.org
......
  Version:                      v1
  Versions:
    Name:     v1
    Served:   true
    Storage:  true
    Name:     v1beta2
    Served:   true
    Storage:  false
....
```

That's better to upgrade the tfjobs version to `v1` in the mnist example, otherwiase will print below error message while applying the exmaple 
```bash
[root@jinchi1 S3]# kustomize build . |kubectl apply -f -
configmap/mnist-map-training-5hb8dfd8kg created
secret/aws-creds-hk7k7f7f78 created
error: unable to recognize "STDIN": no matches for kind "TFJob" in version "kubeflow.org/v1beta1"
```

**Comment by jinchihe** [comment]
I found the automation tests kubernetes logo
`kubeflow-examples-presubmit`  also faild because of this. 

```
error: unable to recognize "STDIN": no matches for kind "TFJob" in version "kubeflow.org/v1beta1"
ERROR|2019-06-05T06:51:54|/mnt/test-data-volume/kubeflow-examples-presubmit-mnist-566-dd56e69-2464-bf2b/src/kubeflow/tf-operator/py/kubef
low/tf_operator/test_runner.py|72| There was a problem running the job; Exception Command 'kustomize build /mnt/test-data-volume/kubeflow
-examples-presubmit-mnist-566-dd56e69-2464-bf2b/src/kubeflow/examples/mnist/training/GCS| kubectl apply -f -' returned non-zero exit stat
us 1
Traceback (most recent call last):
 File "/mnt/test-data-volume/kubeflow-examples-presubmit-mnist-566-dd56e69-2464-bf2b/src/kubeflow/tf-operator/py/kubeflow/tf_operator/tes
t_runner.py", line 53, in run_test
   test_func()
 File "tfjob_test.py", line 96, in test_train
   subprocess.check_call(subCmd, shell=True)
 File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
   raise CalledProcessError(retcode, cmd)
CalledProcessError: Command 'kustomize build /mnt/test-data-volume/kubeflow-examples-presubmit-mnist-566-dd56e69-2464-bf2b/src/kubeflow/e
xamples/mnist/training/GCS| kubectl apply -f -' returned non-zero exit status 1
```
