### ISSUE TITLE
No signal about xgboost_synthetic test in periodic dashboard and its failing

### ISSUE THREAD

**Issue by jlewi** [kubeflow/examples#665]
We'd like to get the xgboost_synthetic test green as a signal for the 0.7 release.

It's currently not showing up in the dashboard.
https://k8s-testgrid.appspot.com/sig-big-data#kubeflow-periodic-examples

Looking at a recent periodic run
https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/kubeflow-periodic-examples/1184996802630258692

the workflow is triggered but is failing. The step execute_notebook is failing.

**Comment by jlewi** [comment]
Here are the logs
[kubeflow-periodic-examples-xgboost2-8692-4528-2325042608.log.txt](https://github.com/kubeflow/examples/files/3744641/kubeflow-periodic-examples-xgboost2-8692-4528-2325042608.log.txt)

```
2019-10-18T01:01:14.222959982Z  main            INFO:root:Running: kubectl apply -f generated.yaml
2019-10-18T01:01:14.223004657Z  main            cwd=/mnt/test-data-volume/kubeflow-periodic-examples-xgboost2-8692-4528/src/kubeflow/examples/xgboost_synthetic/testing
2019-10-18T01:01:14.234125172Z  main            INFO:root:Subprocess output:
2019-10-18T01:01:14.234164086Z  main
2019-10-18T01:01:15.092262907Z  main            INFO:root:error: SchemaError(io.k8s.api.policy.v1beta1.AllowedCSIDriver): invalid object doesn't have additional properties
2019-10-18T01:01:16.106069678Z  main            Traceback (most recent call last):
                                                  File "xgboost_test.py", line 99, in <module>
                                                    create_job(args, app_dir)
                                                  File "xgboost_test.py", line 29, in create_job
                                                    util.run(['kubectl', 'apply', '-f', 'generated.yaml'], cwd=app_dir)
                                                  File "/mnt/test-data-volume/kubeflow-periodic-examples-xgboost2-8692-4528/src/kubeflow/testing/py/kubeflow/testing/util.py", line 84, in run
                                                    " ".join(command), process.returncode), "\n".join(output))
                                                subprocess.CalledProcessError: Command 'cmd: kubectl apply -f generated.yaml exited with code 1' returned non-zero exit status 1
2019-10-18T01:01:16.389127828Z  wait            time="2019-10-18T01:01:16Z" level=info msg="Main container completed"

So one problem is that the step isn't using pytest
https://github.com/kubeflow/examples/blob/master/xgboost_synthetic/testing/xgboost_test.py

So we won't create a junit file
```

**Comment by jinchihe** [comment]
@jlewi Oh... we should enhance that. 

we also met that in the mnist CI/CD testing, I'm going to debugging in https://github.com/kubeflow/examples/pull/668. I guess that's caused by too old kubectl.

**Comment by jlewi** [comment]
@gabrielwen any update on this? Did your recent PRs resolve this?
